export const POST_REQUEST = 'POST_REQUEST'
export const POST_SUCCESS = "POST_SUCCESS"
export const POST_FAIL = "POST_FAIL"

export const GET_POST_REQUEST = 'GET_POST_REQUEST'
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAIL = "GET_POST_FAIL"
