export const POST_REQUEST = 'POST_REQUEST'
export const POST_SUCCESS = "POST_SUCCESS"
export const POST_FAIL = "POST_FAIL"

export const GET_POST_REQUEST = 'GET_POST_REQUEST'
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAIL = "GET_POST_FAIL"

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"
export const DELETE_POST_FAIL = "DELETE_POST_FAIL"

export const POST_SIGN_OUT = "POST_SIGN_OUT"